### ISSUE TITLE
[BUG] sony android10 TV 安装1.6.0打开闪退  ,更换1.5.8同样

### ISSUE THREAD

**Issue by myHooby** [lizongying/my-tv#385]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

最新稳定版

### Bug 描述

[BUG] sony android10 TV 安装1.6.0打开闪退  ,更换1.5.8同样。

### 预期行为

正常打开

### 实际行为

闪退

### 复现步骤

打开即闪退

### UI / OS

SONY

### Android 版本

10

**Comment by busuzhike130** [comment]
用电视盒子一样闪退，打不开

**Comment by myHooby** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by klren0312** [comment]
遇到同样问题
```
java.lang.NullPointerException
	at com.lizongying.mytv.Request$fetchToken$1.onResponse(Request.kt:376)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$1.run(DefaultCallAdapterFactory.java:83)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8152)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
```

**Comment by dustxdustx** [comment]
OPPO k9同样问题，退回1.58同样闪退

**Comment by ganhaile** [comment]
俺也一样也是索尼电视

**Comment by awmc233** [comment]
AndroidTV8也一样（原生安卓TV8）

**Comment by lizongying** [comment]
服務器帶寬打滿了，已升級。重新使用打開軟件即可。
