### ISSUE TITLE
[BUG] 天猫魔屏闪退

### ISSUE THREAD

**Issue by 938134** [lizongying/my-tv#616]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

天猫魔屏N1pro android9安装后，启动时闪退

### 预期行为

正常启动

### 实际行为

闪退

### UI / OS

天猫魔屏

### Android 版本

9.0

**Comment by lizongying** [comment]
天貓的問題確實比較多。
這個yunos和正常的安卓還是有區別的，之前發現它替換了谷歌的一個組件會導致閃退，而高於此版本和低於此版本的設備還有正常的，這就不好處理了，不確定哪些版本受此影響，索性所有檢測到天貓品牌，都用了低版本的播放器，至少能用了。
後面還是有很多天貓設備沒法用，我也不知道怎麼處理了，因為根本不知道這些設備又是什麼問題。
我買了個二手的天貓盒子，還有熱心網友發過來的一個，測試是能用的，其他的就沒辦法了。
有可能的話，把具體的錯誤日誌給我，我盡可能嘗試解決下。

**Comment by linjinya** [comment]
一样的N1投影机！
我之前就发了天猫魔屏N1，装好后打开闪退！

**Comment by fuunnyy** [comment]
同样碰到了闪退问题。闪退堆栈信息如下。

````
2024-04-04 21:02:40.654 11825-11825 dalvikvm                com.lizongying.mytv                  W  Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Lcom/lizongying/mytv/Request;
2024-04-04 21:02:40.654 11825-11825 AndroidRuntime          com.lizongying.mytv                  E  FATAL EXCEPTION: main
                                                                                                    Process: com.lizongying.mytv, PID: 11825
                                                                                                    java.lang.NoClassDefFoundError: okhttp3.internal.platform.Platform
                                                                                                    	at okhttp3.internal.tls.CertificateChainCleaner.get(CertificateChainCleaner.java:41)
                                                                                                    	at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.java:782)
                                                                                                    	at com.lizongying.mytv.api.ApiClient.getUnsafeOkHttpClient(ApiClient.kt:144)
                                                                                                    	at com.lizongying.mytv.api.ApiClient.<init>(ApiClient.kt:28)
                                                                                                    	at com.lizongying.mytv.Request.<clinit>(Request.kt:39)
                                                                                                    	at com.lizongying.mytv.MainActivity.onCreate(MainActivity.kt:61)
````

**Comment by haahaa99** [comment]
請問這個問題會修復嗎?
