### ISSUE TITLE
[BUG] Android 4.3无法启动

### ISSUE THREAD

**Issue by choury** [lizongying/my-tv#629]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

I/ActivityManager( 1580): Start proc com.lizongying.mytv for activity com.lizongying.mytv/.MainActivity: pid=3828 uid=10005 gids={50005, 3003, 1015, 1028}
E/AndroidRuntime( 3828): FATAL EXCEPTION: main
E/AndroidRuntime( 3828): java.lang.ExceptionInInitializerError
E/AndroidRuntime( 3828): 	at okhttp3.internal.tls.CertificateChainCleaner.get(CertificateChainCleaner.java:41)
E/AndroidRuntime( 3828): 	at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.java:782)
E/AndroidRuntime( 3828): 	at com.lizongying.mytv.api.ApiClient.getUnsafeOkHttpClient(ApiClient.kt:130)
E/AndroidRuntime( 3828): 	at com.lizongying.mytv.api.ApiClient.<init>(ApiClient.kt:24)
E/AndroidRuntime( 3828): 	at com.lizongying.mytv.Request.<clinit>(Request.kt:38)
E/AndroidRuntime( 3828): 	at com.lizongying.mytv.MainActivity.onCreate(MainActivity.kt:40)
E/AndroidRuntime( 3828): 	at android.app.Activity.performCreate(Activity.java:5145)
E/AndroidRuntime( 3828): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
E/AndroidRuntime( 3828): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2185)
E/AndroidRuntime( 3828): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
E/AndroidRuntime( 3828): 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
E/AndroidRuntime( 3828): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1260)
E/AndroidRuntime( 3828): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 3828): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 3828): 	at android.app.ActivityThread.main(ActivityThread.java:5114)
E/AndroidRuntime( 3828): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3828): 	at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime( 3828): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:773)
E/AndroidRuntime( 3828): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:589)
E/AndroidRuntime( 3828): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 3828): Caused by: java.lang.NullPointerException: No platform found on Android
E/AndroidRuntime( 3828): 	at okhttp3.internal.platform.Platform.findAndroidPlatform(Platform.java:250)
E/AndroidRuntime( 3828): 	at okhttp3.internal.platform.Platform.findPlatform(Platform.java:203)
E/AndroidRuntime( 3828): 	at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
E/AndroidRuntime( 3828): 	... 20 more
I/ActivityManager( 1580): crash dialog of ProcessRecord{42e5f1b8 3828:com.lizongying.mytv/u0a10005},mIsUserBuild = true,isBackgroundProcess = false,mShowDialogs = true,mSleeping = false,mShuttingDown = false
I/ActivityManager( 1580): Killing proc 3828:com.lizongying.mytv/u0a10005: force stop com.lizongying.mytv

### 预期行为

能正常使用

### 实际行为

crash

### UI / OS

乐视 X50 Air

### Android 版本

4.3

**Comment by choury** [comment]
It works with 1.7.2
