### ISSUE TITLE
退出时报错 Android11

### ISSUE THREAD

**Issue by liqiangsky** [lizongying/my-tv#74]
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2080)
	at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2106)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:683)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:637)
	at com.lizongying.mytv.MainActivity.hideRunnable$lambda$0(MainActivity.kt:108)
	at com.lizongying.mytv.MainActivity.$r8$lambda$C_8_Gt_Xctch1IwSB1O9qOWdctA(Unknown Source:0)
	at com.lizongying.mytv.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8060)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by liqiangsky** [comment]
还有退出到后台再打开不播放

**Comment by lizongying** [comment]
@liqiangsky 确实有错误，没大影响就一直没修复，后面会处理的。

**Comment by JackShell2020** [comment]
退出后 黑屏，是这问题吗，大佬什么时候解决一下。    创维酷开系统
