### ISSUE TITLE
[BUG] v2.0.5创维 9R15_E710U 电视打开之后 Crash

### ISSUE THREAD

**Issue by VomPom** [lizongying/my-tv#807]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

```
2024-05-25 11:49:50.643  1668-2087  ActivityThread          com.tianci.system                    E  Failed to find provider info for com.tianci.logcatcher.ProviderAuth
2024-05-25 11:49:50.643 16880-16880 MainActivity            com.lizongying.mytv                  I  ready request 6 
2024-05-25 11:49:50.643  1668-2087  ActivityThread          com.tianci.system                    E  Failed to find provider info for com.tianci.logcatcher.ProviderAuth
2024-05-25 11:49:50.703 16880-16880 libEGL                  com.lizongying.mytv                  D  >>> 0 0 android
2024-05-25 11:49:50.703 16880-16880 libEGL                  com.lizongying.mytv                  D  >>> 0 1 POWERVR_SGX544_115
2024-05-25 11:49:50.719 16880-16880 libEGL                  com.lizongying.mytv                  D  loaded /system/lib/egl/libEGL_POWERVR_SGX544_115.so
2024-05-25 11:49:50.723 16880-16880 libEGL                  com.lizongying.mytv                  D  loaded /system/lib/egl/libGLESv1_CM_POWERVR_SGX544_115.so
2024-05-25 11:49:50.727 16880-16880 libEGL                  com.lizongying.mytv                  D  loaded /system/lib/egl/libGLESv2_POWERVR_SGX544_115.so
2024-05-25 11:49:50.775  2067-2577  CursorWindow            com.tianci.appstore                  E  Failed to read row 0, column -1 from a CursorWindow which has 3 rows, 23 columns.
2024-05-25 11:49:50.899 16880-16880 OpenGLRenderer          com.lizongying.mytv                  D  Enabling debug mode 0
2024-05-25 11:49:51.191 16880-16880 dalvikvm                com.lizongying.mytv                  W  Unable to resolve superclass of Landroidx/media3/exoplayer/ExoPlayerImpl$NoSuitableOutputPlaybackSuppressionAudioDeviceCallback; (275)
2024-05-25 11:49:51.191 16880-16880 dalvikvm                com.lizongying.mytv                  W  Link of class 'Landroidx/media3/exoplayer/ExoPlayerImpl$NoSuitableOutputPlaybackSuppressionAudioDeviceCallback;' failed
2024-05-25 11:49:51.191 16880-16880 dalvikvm                com.lizongying.mytv                  E  Could not find class 'androidx.media3.exoplayer.ExoPlayerImpl$NoSuitableOutputPlaybackSuppressionAudioDeviceCallback', referenced from method androidx.media3.exoplayer.ExoPlayerImpl.<init>
2024-05-25 11:49:51.191 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to resolve new-instance 4863 (Landroidx/media3/exoplayer/ExoPlayerImpl$NoSuitableOutputPlaybackSuppressionAudioDeviceCallback;) in Landroidx/media3/exoplayer/ExoPlayerImpl;
2024-05-25 11:49:51.191 16880-16880 dalvikvm                com.lizongying.mytv                  D  VFY: replacing opcode 0x22 at 0x0299
2024-05-25 11:49:51.207 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature ([Landroid/media/AudioDeviceInfo;)
2024-05-25 11:49:51.207 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature ([Landroid/media/AudioDeviceInfo;)
2024-05-25 11:49:51.319 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/media/AudioDeviceInfo;)
2024-05-25 11:49:51.323 16880-16880 dalvikvm                com.lizongying.mytv                  W  Unable to resolve superclass of Landroidx/media3/exoplayer/ExoPlayerImpl$NoSuitableOutputPlaybackSuppressionAudioDeviceCallback; (275)
2024-05-25 11:49:51.323 16880-16880 dalvikvm                com.lizongying.mytv                  W  Link of class 'Landroidx/media3/exoplayer/ExoPlayerImpl$NoSuitableOutputPlaybackSuppressionAudioDeviceCallback;' failed
2024-05-25 11:49:51.323 16880-16880 dalvikvm                com.lizongying.mytv                  D  DexOpt: unable to opt direct call 0x92c7 at 0x29c in Landroidx/media3/exoplayer/ExoPlayerImpl;.<init>
2024-05-25 11:49:51.323 16880-16880 ExoPlayerImpl           com.lizongying.mytv                  I  Init 32a47928 [AndroidXMedia3/1.2.1] [rtd299x_tv010_4k, 9R15_E710U, Skyworth, 17]
2024-05-25 11:49:51.511 16880-16880 dalvikvm                com.lizongying.mytv                  E  Could not find class 'android.media.PlaybackParams', referenced from method androidx.media3.exoplayer.audio.DefaultAudioSink.setAudioTrackPlaybackParametersV23
2024-05-25 11:49:51.511 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to resolve new-instance 343 (Landroid/media/PlaybackParams;) in Landroidx/media3/exoplayer/audio/DefaultAudioSink;
2024-05-25 11:49:51.511 16880-16880 dalvikvm                com.lizongying.mytv                  D  VFY: replacing opcode 0x22 at 0x0006
2024-05-25 11:49:51.515 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/media/AudioDeviceInfo;)
2024-05-25 11:49:51.515 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/media/AudioDeviceInfo;)
2024-05-25 11:49:51.515 16880-16880 dalvikvm                com.lizongying.mytv                  D  DexOpt: unable to opt direct call 0x0713 at 0x08 in Landroidx/media3/exoplayer/audio/DefaultAudioSink;.setAudioTrackPlaybackParametersV23
2024-05-25 11:49:51.575  4149-4153  dalvikvm                com...mes.api.mpd.ControllerService  D  GC_CONCURRENT freed 397K, 24% free 1368K/1788K, paused 5ms+7ms, total 28ms
2024-05-25 11:49:51.627 16880-16883 dalvikvm                com.lizongying.mytv                  D  GC_CONCURRENT freed 518K, 14% free 3447K/3988K, paused 4ms+3ms, total 185ms
2024-05-25 11:49:51.627 16880-16880 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 79ms
2024-05-25 11:49:51.659 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/view/accessibility/CaptioningManager;)
2024-05-25 11:49:51.659 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/view/accessibility/CaptioningManager;)
2024-05-25 11:49:51.659 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/view/accessibility/CaptioningManager;)
2024-05-25 11:49:51.703 16880-16880 TelephonyManager        com.lizongying.mytv                  D  No /proc/cmdline exception=java.io.FileNotFoundException: /proc/cmdline: open failed: EACCES (Permission denied)
2024-05-25 11:49:51.703 16880-16880 TelephonyManager        com.lizongying.mytv                  D  /proc/cmdline=
2024-05-25 11:49:51.775  2067-2577  CursorWindow            com.tianci.appstore                  E  Failed to read row 0, column -1 from a CursorWindow which has 3 rows, 23 columns.
2024-05-25 11:49:51.811 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/media/AudioFocusRequest;)
2024-05-25 11:49:51.811 16880-16880 dalvikvm                com.lizongying.mytv                  E  Could not find class 'android.media.AudioFocusRequest$Builder', referenced from method androidx.media3.exoplayer.AudioFocusManager.requestAudioFocusV26
2024-05-25 11:49:51.811 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to resolve new-instance 277 (Landroid/media/AudioFocusRequest$Builder;) in Landroidx/media3/exoplayer/AudioFocusManager;
2024-05-25 11:49:51.811 16880-16880 dalvikvm                com.lizongying.mytv                  D  VFY: replacing opcode 0x22 at 0x000a
2024-05-25 11:49:51.811 16880-16880 dalvikvm                com.lizongying.mytv                  E  Could not find class 'android.media.AudioFocusRequest$Builder', referenced from method androidx.media3.exoplayer.AudioFocusManager.requestAudioFocusV26
2024-05-25 11:49:51.811 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to resolve new-instance 277 (Landroid/media/AudioFocusRequest$Builder;) in Landroidx/media3/exoplayer/AudioFocusManager;
2024-05-25 11:49:51.811 16880-16880 dalvikvm                com.lizongying.mytv                  D  VFY: replacing opcode 0x22 at 0x0012
2024-05-25 11:49:51.811 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/media/AudioFocusRequest;)
2024-05-25 11:49:51.815 16880-16880 dalvikvm                com.lizongying.mytv                  D  DexOpt: unable to opt direct call 0x0613 at 0x0e in Landroidx/media3/exoplayer/AudioFocusManager;.requestAudioFocusV26
2024-05-25 11:49:51.815 16880-16880 dalvikvm                com.lizongying.mytv                  D  DexOpt: unable to opt direct call 0x0614 at 0x16 in Landroidx/media3/exoplayer/AudioFocusManager;.requestAudioFocusV26
2024-05-25 11:49:51.827  1355-1696  sky_dialog              system_process                       I  type=1001 uid=10001 pid=16880
2024-05-25 11:49:51.835 16880-16880 Choreographer           com.lizongying.mytv                  I  Skipped 35 frames!  The application may be doing too much work on its main thread.
2024-05-25 11:49:52.163  1355-1373  ActivityManager         system_process                       I  Displayed com.lizongying.mytv/.MainActivity: +4s516ms
2024-05-25 11:49:52.367 16880-16880 MainActivity            com.lizongying.mytv                  I  ready MainFragment 7 
2024-05-25 11:49:52.367 16880-16880 MainFragment            com.lizongying.mytv                  I  switch CCTV1 综合
2024-05-25 11:49:52.367 16880-16880 MainFragment            com.lizongying.mytv                  I  request CCTV1 综合
2024-05-25 11:49:52.423 16880-16880 Glide                   com.lizongying.mytv                  W  Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
2024-05-25 11:49:52.427 16880-16901 dalvikvm                com.lizongying.mytv                  I  Could not find method com.google.gson.Gson.newJsonReader, referenced from method retrofit2.converter.gson.GsonResponseBodyConverter.convert
2024-05-25 11:49:52.427 16880-16901 dalvikvm                com.lizongying.mytv                  W  VFY: unable to resolve virtual method 43: Lcom/google/gson/Gson;.newJsonReader (Ljava/io/Reader;)Lcom/google/gson/stream/JsonReader;
2024-05-25 11:49:52.427 16880-16901 dalvikvm                com.lizongying.mytv                  D  VFY: replacing opcode 0x6e at 0x0006
2024-05-25 11:49:52.475 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/graphics/ColorSpace;)
2024-05-25 11:49:52.479 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/graphics/ColorSpace;)
2024-05-25 11:49:52.479 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/graphics/ColorSpace;)
2024-05-25 11:49:52.479 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/graphics/ColorSpace;)
2024-05-25 11:49:52.479 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/graphics/ColorSpace;)
2024-05-25 11:49:52.479 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/graphics/ColorSpace;)
2024-05-25 11:49:52.479 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/graphics/ColorSpace;)
2024-05-25 11:49:52.479 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/graphics/ColorSpace;)
2024-05-25 11:49:52.479 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/graphics/ColorSpace;)
2024-05-25 11:49:52.479 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/graphics/ColorSpace;)
2024-05-25 11:49:52.479 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/graphics/ColorSpace;)
2024-05-25 11:49:52.479 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/graphics/ColorSpace;)
2024-05-25 11:49:52.479 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/graphics/ColorSpace;)
2024-05-25 11:49:52.483 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/graphics/ColorSpace;)
2024-05-25 11:49:52.483 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/graphics/ColorSpace;)
2024-05-25 11:49:52.483 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/graphics/ColorSpace;)
2024-05-25 11:49:52.483 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/graphics/ColorSpace;)
2024-05-25 11:49:52.483 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/graphics/ColorSpace;)
2024-05-25 11:49:52.483 16880-16880 dalvikvm                com.lizongying.mytv                  W  VFY: unable to find class referenced in signature (Landroid/graphics/ColorSpace;)
2024-05-25 11:49:52.503 16880-16883 dalvikvm                com.lizongying.mytv                  D  GC_CONCURRENT freed 555K, 13% free 3883K/4460K, paused 6ms+10ms, total 44ms
2024-05-25 11:49:52.523 16880-16880 InfoFragment            com.lizongying.mytv                  I  CCTV1 综合 null
2024-05-25 11:49:52.779  2067-2577  CursorWindow            com.tianci.appstore                  E  Failed to read row 0, column -1 from a CursorWindow which has 3 rows, 23 columns.
2024-05-25 11:49:52.823 16880-16883 dalvikvm                com.lizongying.mytv                  D  GC_CONCURRENT freed 795K, 15% free 4327K/5044K, paused 8ms+21ms, total 92ms
2024-05-25 11:49:52.823 16880-16974 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 31ms
2024-05-25 11:49:52.827 16880-16972 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 33ms
2024-05-25 11:49:52.827 16880-16975 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 34ms
2024-05-25 11:49:52.883 16880-16980 dalvikvm                com.lizongying.mytv                  I  Could not find method sun.misc.Unsafe.allocateInstance, referenced from method com.google.protobuf.UnsafeUtil.allocateInstance
2024-05-25 11:49:52.883 16880-16980 dalvikvm                com.lizongying.mytv                  W  VFY: unable to resolve virtual method 62656: Lsun/misc/Unsafe;.allocateInstance (Ljava/lang/Class;)Ljava/lang/Object;
2024-05-25 11:49:52.883 16880-16980 dalvikvm                com.lizongying.mytv                  D  VFY: replacing opcode 0x6e at 0x0002
2024-05-25 11:49:52.911 16880-16972 dalvikvm                com.lizongying.mytv                  W  threadid=21: thread exiting with uncaught exception (group=0x326bc930)
2024-05-25 11:49:52.915 16880-16972 AndroidRuntime          com.lizongying.mytv                  E  FATAL EXCEPTION: OkHttp Dispatcher
                                                                                                    java.lang.NoSuchMethodError: com.google.gson.Gson.newJsonReader
                                                                                                    	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
                                                                                                    	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
                                                                                                    	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
                                                                                                    	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:121)
                                                                                                    	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
                                                                                                    	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                                                    	at java.lang.Thread.run(Thread.java:856)
2024-05-25 11:49:52.915  1355-2012  ActivityManager         system_process                       W    Force finishing activity com.lizongying.mytv/.MainActivity
2024-05-25 11:49:53.015  1355-1374  sky_dialog              system_process                       I  type=2003 uid=1000 pid=1355
2024-05-25 11:49:53.015  1355-1374  sky_dialog              system_process                       I  status=100
2024-05-25 11:49:53.015  1355-1374  sky_dialog              system_process                       I  pid=1355 is ApplicationShowing. +status=100
2024-05-25 11:49:53.063  1355-1374  KeyEvent                system_process                       V  Reset: android.view.KeyEvent$DispatcherState@32b2c710
2024-05-25 11:49:53.175 16880-16883 dalvikvm                com.lizongying.mytv                  D  GC_CONCURRENT freed 871K, 16% free 4742K/5636K, paused 7ms+4ms, total 108ms
2024-05-25 11:49:53.175 16880-16978 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 79ms
2024-05-25 11:49:53.175 16880-16975 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 81ms
2024-05-25 11:49:53.175 16880-16988 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 81ms
2024-05-25 11:49:53.179 16880-16989 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 85ms
2024-05-25 11:49:53.179 16880-16895 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 35ms
2024-05-25 11:49:53.179 16880-16980 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 85ms
2024-05-25 11:49:53.183 16880-16984 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 86ms
2024-05-25 11:49:53.183 16880-16880 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 86ms
2024-05-25 11:49:53.287  2726-2726  wpa_supplicant          pid-2726                             I  [CTRL_IFACE]wlan0: SIGNAL_POLL
2024-05-25 11:49:53.459 16880-16883 dalvikvm                com.lizongying.mytv                  D  GC_CONCURRENT freed 841K, 14% free 5328K/6192K, paused 7ms+6ms, total 80ms
2024-05-25 11:49:53.459 16880-16978 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 52ms
2024-05-25 11:49:53.463 16880-16974 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 54ms
2024-05-25 11:49:53.463 16880-16991 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 55ms
2024-05-25 11:49:53.463 16880-16880 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 54ms
2024-05-25 11:49:53.463 16880-17000 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 43ms
2024-05-25 11:49:53.463 16880-16999 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 29ms
2024-05-25 11:49:53.463 16880-16996 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 44ms
2024-05-25 11:49:53.463 16880-16992 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 51ms
2024-05-25 11:49:53.463 16880-16993 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 56ms
2024-05-25 11:49:53.467 16880-16994 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 57ms
2024-05-25 11:49:53.467 16880-16995 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 47ms
2024-05-25 11:49:53.467 16880-16984 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 47ms
2024-05-25 11:49:53.467 16880-16977 dalvikvm                com.lizongying.mytv                  D  WAIT_FOR_CONCURRENT_GC blocked 30ms
2024-05-25 11:49:53.495 16880-16880 KeyEvent                com.lizongying.mytv                  V  Reset: android.view.KeyEvent$DispatcherState@3299af48
```

### 预期行为

正常运行

### 实际行为

打开进入就crash
![Screenshot_20240525_115855](https://github.com/lizongying/my-tv/assets/27652454/49128419-2bdc-48a5-860b-c30ae9f4669a)

### 复现步骤

正常安装运行

### UI / OS

Skyworth(创维)

### Android 版本

Android 4.2   SDK level 17

### 额外信息

看日志是 Gson 库兼容相关的问题，App源码工程是   minSdk 21，电视是17，可能需要向下兼容，电脑挺老的，不过一直能正常流畅的运行其他应用

**Comment by jizhujian** [comment]
请问怎样跟踪日志，创维酷开50U2同样的问题，android5.0.1

**Comment by lizongying** [comment]
gson的版本是2.8.5 最低是19，17待驗證

**Comment by VomPom** [comment]
> 请问怎样跟踪日志，创维酷开50U2同样的问题，android5.0.1

电视 adb 模式打开，并找到 ip 信息，使用 adb connect 连接到对应的 ip，使用 logcat 即可捕获日志

**Comment by jizhujian** [comment]
创维酷开50U2，Android5.0.1同样的错误
E/AndroidRuntime(21445): FATAL EXCEPTION: OkHttp Dispatcher
E/AndroidRuntime(21445): Process: com.lizongying.mytv, PID: 21445
E/AndroidRuntime(21445): java.lang.NoSuchMethodError: No virtual method newJsonReader(Ljava/io/Reader;)Lcom/google/gson/stream/JsonReader; in class Lcom/google/gson/Gson; or its super classes (declaration of 'com.google.gson.Gson' appears in /system/framework/skyworthdigital.jar)
E/AndroidRuntime(21445):        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
E/AndroidRuntime(21445):        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
E/AndroidRuntime(21445):        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
E/AndroidRuntime(21445):        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:121)
E/AndroidRuntime(21445):        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
E/AndroidRuntime(21445):        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
E/AndroidRuntime(21445):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(21445):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(21445):        at java.lang.Thread.run(Thread.java:818)

**Comment by lizongying** [comment]
大概知道原因了，電視的Gson導致的，我看看怎麼解決

**Comment by lizongying** [comment]
大家可以試試2.0.7，應該能解決這個問題。

**Comment by jizhujian** [comment]
还是同样的错误

**Comment by jizhujian** [comment]
还是同样的错误
`E/AndroidRuntime( 5330): FATAL EXCEPTION: OkHttp Dispatcher
E/AndroidRuntime( 5330): Process: com.lizongying.mytv, PID: 5330
E/AndroidRuntime( 5330): java.lang.NoSuchMethodError: No virtual method newJsonReader(Ljava/io/Reader;)Lcom/google/gson/stream/JsonReader; in class Lcom/google/gson/Gson; or its super classes (declaration of 'com.google.gson.Gson' appears in /system/framework/skyworthdigital.jar)
E/AndroidRuntime( 5330):        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
E/AndroidRuntime( 5330):        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
E/AndroidRuntime( 5330):        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
E/AndroidRuntime( 5330):        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:121)
E/AndroidRuntime( 5330):        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
E/AndroidRuntime( 5330):        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
E/AndroidRuntime( 5330):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 5330):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 5330):        at java.lang.Thread.run(Thread.java:818)
W/ActivityManager( 1623):   Force finishing activity com.lizongying.mytv/.MainActivity`

**Comment by jizhujian** [comment]
还是同样的错误
E/AndroidRuntime( 5330): FATAL EXCEPTION: OkHttp Dispatcher
E/AndroidRuntime( 5330): Process: com.lizongying.mytv, PID: 5330
E/AndroidRuntime( 5330): java.lang.NoSuchMethodError: No virtual method newJsonReader(Ljava/io/Reader;)Lcom/google/gson/stream/JsonReader; in class Lcom/google/gson/Gson; or its super classes (declaration of 'com.google.gson.Gson' appears in /system/framework/skyworthdigital.jar)
E/AndroidRuntime( 5330):        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
E/AndroidRuntime( 5330):        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
E/AndroidRuntime( 5330):        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
E/AndroidRuntime( 5330):        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:121)
E/AndroidRuntime( 5330):        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
E/AndroidRuntime( 5330):        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
E/AndroidRuntime( 5330):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 5330):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 5330):        at java.lang.Thread.run(Thread.java:818)
W/ActivityManager( 1623):   Force finishing activity com.lizongying.mytv/.MainActivity

**Comment by lizongying** [comment]
2.0.8

**Comment by jizhujian** [comment]
同样的错误

**Comment by jizhujian** [comment]
2.0.9 同样的报错

**Comment by lizongying** [comment]
那就沒辦法了

**Comment by jizhujian** [comment]
感谢！

**Comment by jizhujian** [comment]
可否试一下更换gson为jackson

https://square.github.io/retrofit/

CONVERTERS
By default, Retrofit can only deserialize HTTP bodies into OkHttp's ResponseBody type and it can only accept its RequestBody type for @Body.

Converters can be added to support other types. Sibling modules adapt popular serialization libraries for your convenience.

com.squareup.retrofit2:converter-gson
com.squareup.retrofit2:converter-jackson
...

Retrofit retrofit = new Retrofit.Builder()
    ...
    .addConverterFactory(GsonConverterFactory.create())  ==> 改成jacksonConvertery试试
    .build();

**Comment by jizhujian** [comment]
报错源找到了

https://github.com/square/retrofit/blob/trunk/retrofit-converters/gson/src/main/java/retrofit2/converter/gson/GsonResponseBodyConverter.java

  public T convert(ResponseBody value) throws IOException {
    JsonReader jsonReader = gson.newJsonReader(value.charStream());

**Comment by jizhujian** [comment]
源代码缺少 src/main/cpp/native.c 和 src/main/cpp/aes.c 两个文件，编译不了
