### ISSUE TITLE
[BUG] v2.1.6在小米手机上闪退，附堆栈信息

### ISSUE THREAD

**Issue by hughcontek** [lizongying/my-tv#876]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### my-ty 版本

通用版

### Bug 描述

在Release下载的v2.1.6版本，安装在小米手机上，打开闪退。

> java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at com.lizongying.mytv.requests.Request$fetchVideo$2.onResponse(Request.kt:339)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$1.run(DefaultCallAdapterFactory.java:83)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8767)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

### 预期行为

启动

### 实际行为

闪退

### UI / OS

XiaoMi HyperOS 1.0.9.0

### Android 版本

14

**Comment by hughcontek** [comment]
更新：安装使用 2.1.6-10-hd-debug.apk 后正常
